server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:

        # Route for /api/auth/** to auth-service
        - id: auth-service-route
          uri: http://auth-service:4005 #Internal address of service where it is running
          predicates:
            - Path=/auth/** # Request with this predicate forworded to internal address of service
          filters:
            - StripPrefix=1  # When request url go to internal address it removes all prefix from url and keep only last one

               ## Req comes at api gateway -> http://localhost:4004/auth/login
               ## Req api gateway sends to internal server is -> http://auth-service:4005/login

        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation  # -> We use where we need the validation on endpoint
                             # -> All requests coming to this url is Authorized

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # Route for /api/docs/auth to auth-service /v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs



# auth: # -> We can Add this to env variables of gateway-service to tell where you have auth service
#  service:   # for JwtValidation
#    url: http://auth-service:4005