spring.application.name=patient-service

# UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Overridden in Docker by SPRING_DATA_REDIS_HOST=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# --- temporary, for learning: lets us SEE the cache working ---
spring.jpa.show-sql=true
logging.level.org.springframework.cache=TRACE

server.port=4000
logging.level.root=info